name = "mehmetbaker_dev"
main = "index.js"
compatibility_date = "2022-05-03"

workers_dev = false

[site]
bucket = "./public"

[env.production]
name = "mehmetbaker_dev-production"
route = "https://*mehmetbaker.dev/*"
