name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      name: Checkout the repository

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn

    - name: Publish the website
      run: yarn deploy
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} 
