name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Job
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout the repository

    - name: Set up Node.js version
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - name: Setup wrangler
      run: npm install --global @cloudflare/wrangler@1.19.8

    - name: Install dependencies
      run: npm install

    - name: Publish the website
      run: wrangler publish --env production
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }} 
